//! Compile-time pinning of the RFC-3161 TSA root certificates.
//!
//! Compiled for every build, but only does real work under the `tsa` feature
//! (the only build that links the verifier). It:
//!
//! 1. reads `roots/roots.toml` (the manifest) and each referenced `roots/*.der`,
//! 2. asserts each DER parses as an X.509 `Certificate`,
//! 3. asserts each DER's SHA-256 equals the manifest's `sha256_fingerprint`
//!    (FAILING THE BUILD on any drift — a swapped or corrupted root cannot slip
//!    in silently), and
//! 4. emits `$OUT_DIR/pinned_tsa_roots.rs` exposing
//!    `pub static PINNED_TSA_ROOTS: &[&[u8]]` via `include_bytes!`, so the pinned
//!    DER is embedded straight into the binary.
//!
//! Under `not(feature = "tsa")` it emits an EMPTY slice — no placeholder bytes
//! are ever left in the tree or the binary.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("pinned_tsa_roots.rs");

    // The manifest and DER files only matter under the `tsa` feature; that is
    // the only build that links the verifier and embeds the roots.
    if env::var_os("CARGO_FEATURE_TSA").is_some() {
        emit_pinned_roots(&dest);
    } else {
        // No `tsa` feature: emit an empty trust set. No placeholder literals.
        fs::write(
            &dest,
            "/// No pinned TSA roots in this build (the `tsa` feature is off).\n\
             pub static PINNED_TSA_ROOTS: &[&[u8]] = &[];\n",
        )
        .expect("write empty pinned_tsa_roots.rs");
    }
}

#[cfg(not(feature = "tsa"))]
fn emit_pinned_roots(_dest: &Path) {
    unreachable!("emit_pinned_roots is only reached when CARGO_FEATURE_TSA is set");
}

#[cfg(feature = "tsa")]
fn emit_pinned_roots(dest: &Path) {
    use sha2::{Digest, Sha256};
    use x509_cert::der::Decode;
    use x509_cert::Certificate;

    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));
    let roots_dir = manifest_dir.join("roots");
    let manifest_path = roots_dir.join("roots.toml");

    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let manifest_text =
        fs::read_to_string(&manifest_path).unwrap_or_else(|e| panic!("read roots.toml: {e}"));
    let manifest: Manifest = toml::from_str(&manifest_text)
        .unwrap_or_else(|e| panic!("parse roots.toml: {e}"));

    assert!(
        !manifest.root.is_empty(),
        "roots.toml pins no TSA roots — the verifier would have no trust anchor"
    );

    // Build the generated file: an absolute include_bytes! per root + the slice.
    let mut body = String::new();
    body.push_str("// @generated by build.rs — do not edit. Pinned RFC-3161 TSA roots.\n");

    let mut idents = Vec::with_capacity(manifest.root.len());
    for (i, root) in manifest.root.iter().enumerate() {
        let der_path = roots_dir.join(&root.file);
        println!("cargo:rerun-if-changed={}", der_path.display());

        let der = fs::read(&der_path)
            .unwrap_or_else(|e| panic!("read pinned root `{}`: {e}", root.file));

        // (2) must parse as a real X.509 certificate.
        Certificate::from_der(&der).unwrap_or_else(|e| {
            panic!("pinned root `{}` is not a valid X.509 certificate: {e}", root.file)
        });

        // (3) SHA-256 must equal the manifest pin — fail the build on drift.
        let got = hex_lower(&Sha256::digest(&der));
        let want = root.sha256_fingerprint.to_ascii_lowercase();
        assert_eq!(
            got, want,
            "PINNED ROOT DRIFT for `{}` ({}): file SHA-256 {got} != manifest pin {want}. \
             Refusing to build — re-fetch the root and update roots.toml only after \
             cross-checking the new fingerprint.",
            root.file, root.subject_cn
        );

        let ident = format!("ROOT_{i}");
        body.push_str(&format!(
            "/// {} ({}) — SHA-256 {}\n\
             static {ident}: &[u8] = include_bytes!(r\"{}\");\n",
            root.subject_cn,
            root.vendor,
            want,
            der_path.display(),
        ));
        idents.push(ident);
    }

    body.push_str(
        "/// DER bytes of the pinned RFC-3161 TSA root certificates (validated at\n\
         /// compile time against roots/roots.toml).\n\
         pub static PINNED_TSA_ROOTS: &[&[u8]] = &[\n",
    );
    for ident in &idents {
        body.push_str(&format!("    {ident},\n"));
    }
    body.push_str("];\n");

    fs::write(dest, body).expect("write pinned_tsa_roots.rs");
}

#[cfg(feature = "tsa")]
#[derive(serde::Deserialize)]
struct Manifest {
    #[serde(default)]
    root: Vec<RootEntry>,
}

#[cfg(feature = "tsa")]
#[derive(serde::Deserialize)]
struct RootEntry {
    vendor: String,
    subject_cn: String,
    file: String,
    sha256_fingerprint: String,
    #[allow(dead_code)]
    source_url: String,
}

#[cfg(feature = "tsa")]
fn hex_lower(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}
